accounts/urls.py
from django.urls import path
from .views import login_view, logout_view, register_view



app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
]

daily_news/urls.py
from django.urls import path
from .views import news_detail_view, news_create_view
from news.views import home_view




app_name = 'daily_news'

urlpatterns = [
    path('', home_view, name='home'),
    path('create/', news_create_view, name='create'), 
    path('<int:id>/', news_detail_view, name='detail')
]

news/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view

urlpatterns = [
    path('', home_view, name='main-home'),
    path('admin/', admin.site.urls),
    path('daily_news/', include('daily_news.urls')),
    path('accounts/', include('accounts.urls'))
]

accounts/models.py
# from django.db import models
# from django.contrib.auth.models import User

comments/models.py
from django.db import models

# Create your models here.

daily_news/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class News(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100)
    content = models.TextField(default='')
    publish_date = models.DateTimeField(default='')
    timestamp = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    # upvotes = models.ManyToManyField(User,)
    # downvotes
    # likes = models.ManyToManyField(User,)
    
    def get_absolute_url(self):
        return reverse("daily_news:detail", kwargs={"id": self.id})
    
    def __str__(self):
        return self.title
    
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    othername = models.CharField(max_length=120)
    username = models.CharField( max_length=120, unique=True, null=False)
    bio = models.TextField()
    date_of_birth = models.DateField()
    timestamp = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
 
    def __str__(self):
        return str(self.user)
        

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label='email')
    birthdate = forms.DateField()
    

daily_news/forms.py
from django import forms
from .models import News

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'content', 'publish_date']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
# from django.contrib.auth.forms import UserCreationForm
from .forms import RegistrationForm


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is None:
            message = {
                'error':'Invalid login credentials.'
            }
            return render(request, 'accounts/login.html', message) 
        login(request, user)
        return redirect('daily_news:home')
    return render(request, 'accounts/login.html', {} )


def logout_view(request):
    if request.method == 'POST':
       logout(request)
       return redirect('main-home')
    return render(request, 'accounts/logout.html', {} )


def register_view(request):
    form = RegistrationForm(request.POST or None)
    if form.is_valid():
        user_object = form.save()
        return redirect('accounts:login')
    context = {
        'form':form
    }
    return render(request, 'accounts/register.html', context)

comments/views.py
from django.shortcuts import render

# Create your views here.

daily_news/views.py
from django.shortcuts import render,redirect
from django.http import Http404
from .models import News
from.forms import NewsForm
from django.contrib.auth.decorators import login_required


def news_detail_view(request, id=None):
    news_obj = None
    if id is not None:
        try:
            news_obj = News.objects.get(id=id)
        except News.DoesNotExist:
            raise Http404
    context = {
        'news':news_obj
    }
    return render(request, 'daily_news/details.html', context)

@login_required
def news_create_view(request):
    form = NewsForm(request.POST or None)
    context = {
        'form':form
    }
    if form.is_valid():
        context['form'] = NewsForm()
        news_obj = form.save()
        return redirect(news_obj.get_absolute_url())
   
    return render(request, 'daily_news/create.html', context)

news/views.py
from django.shortcuts import render
from daily_news.models import News

def home_view(request):
    news_list = News.objects.all()
    print(news_list)
    context = {
        'news':news_list
    }
    return render(request, 'news/home.html', context)

daily_news/templates/daily_news/create.html
{% extends 'base.html' %} 

{% block content %}

{% if user.is_authenticated%}
<h2>Create your news content here</h2>
<div style="margin-top: 30px">
  <form action="." method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div style="margin-top: 5px">
      <input type="submit" value="Add News" />
    </div>
  </form>
</div>

{% endif %}

{% endblock %}

daily_news/templates/daily_news/details.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ news.title }}</h1>
<p>{{ news.content }}</p>

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
<p> {{user.username}} already logged in!</p>
<a href="{% url 'accounts:logout'%}">Logout {{user.username}}? </a>

{% else %}
<form action="" method="post">
    {% csrf_token %}
    {% if error %}
    <p> {{error}} </p>
    {% endif %}
    <div>
        <input type="username" name="username" placeholder="Username"> <br><br><br>
        <input type="password" name="password" placeholder="Password"> <br><br>
        <button type="submit">Login</button>
    </div>
</form>
{% endif %}

{% endblock content %}

templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}

<form action="" method="post">
    {% csrf_token %}
    <p> Are you sure you want to logout?</p> 
    <button type='submit'>Yes, Logout!</button>
</form>

{% else %}

<p>Would you like to <a href= "{% url 'accounts:login' %}">login?</a></p>

{% endif %}

{% endblock content %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}

<form action="." method='POST'>
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Register</button>
</form>


{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily_News</title>
</head>
<body>
    
    <nav>
        <a href="{% url 'daily_news:home'%}">Home</a>
        <a href="{% url 'daily_news:create' %}">Create News</a>
        <a href="{% url 'accounts:login' %}">Login</a>
        <a href="{% url 'accounts:logout' %}">Logout</a>
        <p>Need an account? <a href="{% url 'accounts:register' %}">Register here!</a> </p>
    </nav>
    <hr>
    {% block content%}


    {% endblock %}
</body>
</html>

templates/news/home.html
{% extends 'base.html'%}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<main>
    <h1>
        Welcome {{ user}}, to TDN!
    </h1> 
</main>

{% else %} 
<main>
    <h1>
        Welcome to The-Daily-News 
    </h1>

</main>
 {% endif %}

<div>
    <h3>Recent Uploads</h3>
</div>

{% for item in news%}
<div>
    <ul>
        <li>
        <a href='{{item.get_absolute_url}}'>{{ item.title }}</a> 
        </li>
    </ul>
</div>
{% endfor %}
{% endblock %}